Fix compilation error with older csc
On a pre-16.3 csc, the changed code would error out with:

```
 error CS0136: A local or parameter named 'span' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
```